[build]
  command = "npm run build"
  publish = ".next/server/pages"  # Correct publish directory for Next.js

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Required for Next.js API routes and SSR
[[plugins]]
  package = "@netlify/plugin-nextjs"